### ISSUE TITLE
"import synonyms" Error--py3

### ISSUE THREAD

**Issue by shinalone** [huyingxi/Synonyms#18]
# description
import synonyms
>> Synonyms on loading vocab ...
>> Synonyms on loading stopwords ...
Traceback (most recent call last):
  File "C:\Install\Anaconda35\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-e6c3357df047>", line 1, in <module>
    import synonyms
  File "C:\Install\PyCharm 2017.2.4\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Install\Anaconda35\lib\site-packages\synonyms\__init__.py", line 113, in <module>
    _load_stopwords(_fin_stopwords_path)
  File "C:\Install\Anaconda35\lib\site-packages\synonyms\__init__.py", line 108, in _load_stopwords
    stopwords = words.readlines()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x8a in position 2: illegal multibyte sequence

# environment
python3.6;windows10,64bit

import sys
sys.stdout.encoding
Out[6]: 'UTF-8'

* version:
V1.9

# add info: py3.6 & sys.stdout.encoding == 'UTF-8'.

**Comment by Samurais** [comment]
Take a look #17 .
