### ISSUE TITLE
windows库中当词不在词库时错误会被捕捉, linux下直接报错

### ISSUE THREAD

**Issue by Shaun-Chen** [huyingxi/Synonyms#49]
# description

## expected

# solution

# environment

* version:
The commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
Please give more description and screen shots, thanks.

**Comment by Shaun-Chen** [comment]
我windows上面是2.5版本，当一句话里面有某个词不存在w2v model中时，比如：第一个句子为‘玩玩手机,听音乐’，第二个句子为‘比较轻松,听听音乐,玩玩手机’，会提示：“not exist in w2v model: 玩玩”，然后返回匹配相似度为0.646；
但是当我迁移到linux上面时，提示没有2.5版本，我升级到了3.0版本，然后会直接抛出错误，‘word '玩玩' not in vocabulary’，而且不会返回匹配相似值。
这个我需要如何处理，是版本问题么？ 我有什么办法可以在linux上面下载到2.5版本么？谢谢啦

**Comment by Samurais** [comment]
都升级到3.3.6 这个版本吧。

下面是Linux Python2.7 测试结果
![image](https://user-images.githubusercontent.com/3538629/37075855-c5b16824-220e-11e8-9432-24523727c240.png)

**Comment by Shaun-Chen** [comment]
python环境必须是3.6么？ 我linux上面3.4会报错

**Comment by Samurais** [comment]
是的，用  python3.6 吧。
在 py3.4 上有问题。
#46

**Comment by xiaoniuzilo** [comment]
可是python 3.6一样报错啊。。。刚才试了mac os上的python3.5也是报找不到dict.txt的错。
python 3.4，3.5，3.6一样都找不到dict.txt。3.3.6的版本。但是3.3.3在python3.4运行无问题，3.3.4运行的时候也只是出现vocab的错误，删掉多词性就可以正常使用。  
3.3.5，3.3.6就一直是dict.txt找不到。。。。。。

**Comment by Samurais** [comment]
好的，有空会看。
如果您能帮忙解决就更好了。然后创建一个 Pull Request. Thanks.

**Comment by Samurais** [comment]
应该可以了，才发布了一个版本，修复dict.txt路径问题。

```
pip install -U synonyms==3.3.7
```

**Comment by Shaun-Chen** [comment]
现在synonyms==3.3.7 暂时无法下载  pip提示没有当前版本

**Comment by Samurais** [comment]
https://pypi.python.org/pypi/synonyms
已经传上去一个多小时了，是pypi还没有更新好。之前也是，发布几分钟就能下载到最新的。这次还不清楚，为什么等了这么久。

也可以这样安装：
```
wget https://pypi.python.org/packages/5a/b2/f38b1e3698c167c185d0570a96940b77b59b8f4b10311437d8e6def962b2/synonyms-3.3.7.tar.gz#md5=b2a150c7132eedbe5592013f582bbae6
pip install synonyms-3.3.7.tar.gz
```

**Comment by Shaun-Chen** [comment]
我现在直接在3.3.6版本上面更改了，但是遇到了一个问题：
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/python3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/python3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/python3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/python3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/python3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "flask_main.py", line 76, in get_synonym_result
    rate_sc = synonyms.compare(sentence_i, sentence_j)
  File "/usr/local/python3/lib/python3.6/site-packages/synonyms/__init__.py", line 287, in compare
    return _similarity_distance(s1, s2)
  File "/usr/local/python3/lib/python3.6/site-packages/synonyms/__init__.py", line 228, in _similarity_distance
    g = cosine(_flat_sum_array(_get_wv(s1)), _flat_sum_array(_get_wv(s2)))
  File "/usr/local/python3/lib/python3.6/site-packages/synonyms/__init__.py", line 152, in _get_wv
    print("not exist in w2v model: %s" % y_)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 24-26: ordinal not in range(128)

**Comment by Samurais** [comment]
Fixed in 3.3.8

**Comment by Shaun-Chen** [comment]
thank you
